[package]
name = "utxo-to-parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32"
clap = { version = "4.5", features = [ "derive" ] }
env_logger = "0.11"
log = "0.4"
parquet = { version = "54", default-features = false, features = [ "arrow", "zstd" ]}
arrow = { version = "54" }